schema_business = ["id_class",
                "id_education",
                "id_marital-status",
                "id_native-country",
                "id_occupation",
                "id_relationship",
                "id_sex",
                "id_workclass",
                "id_current_data",
                "age",
                "adult.fnlwgt",
                "education-num",
                "capital-gain",
                "capital-loss",
                "hours-per-week"]